ident:
  ver: 2
options:
 # - row_limit: 10
# geoloc: data/geolocalisation-etablissements-premier-et-second-degre.pkl
# geoloc: data/simplifie.pkl
# geoloc: data/complet.pkl
geoloc2: data/data_dict.raw
sources:
 - fichier: data/brevet_%i.xls
   onglets:
   - Sheet
   diplome: brevet
   inv_mention: true
   annees:
   - 2018
   - 2017
   - 2016
#  - fichier: data/bac_%i.xls
#    onglets:
#    - MENTIONS_GT
#    - REUSSITE_GT
#    diplome: general
#    groupes:
#    - S
#    - L
#    - ES
#    backup_group: GT
#    annees:
#    - 2021
#  - fichier: data/bac_%i.xls
#    onglets:
#    - MENTIONS_PRO
#    - REUSSITE_PRO
#    diplome: pro
#    groupes:
#    - PRO
#    annees:
#    - 2021
#  - fichier: data/bac_%i.xls
#    onglets:
#    - MENTIONS_GT
#    - REUSSITE_GT
#    diplome: techno
#    groupes:
#    - STMG
#    - STL
#    - ST2S
#    - STI2D
#    - STD2A
#    - TMD
#    - STHR
#    annees:
#    - 2021
#  - fichier: data/bac_%i.xls
#    onglets:
#    - REUSSITE_GT
#    diplome: general
#    groupes:
#    - S
#    - L
#    - ES
#    backup_group: GT
#    annees:
#    - 2016
#    - 2015
#    - 2014
#    - 2013
#    - 2012
#    - 2011
#    - 2010
#    - 2009
#    - 2008
#  - fichier: data/bac_%i.xls
#    onglets:
#    - REUSSITE_PRO
#    diplome: pro
#    groupes:
#    - PRO
#    annees:
#    - 2016
#    - 2015
#    - 2014
#    - 2013
#    - 2012
#    - 2011
#    - 2010
#    - 2009
#    - 2008
#  - fichier: data/bac_%i.xls
#    onglets:
#    - REUSSITE_GT
#    diplome: techno
#    groupes:
#    - STMG
#    - STL
#    - ST2S
#    - STI2D
#    - STD2A
#    - TMD
#    - STHR
#    annees:
#    - 2016
#    - 2015
#    - 2014
#    - 2013
#    - 2012
#    - 2011
#    - 2010
#    - 2009
#    - 2008
