# Stage 1: Build
FROM python:3.11

ARG LOGFIRE_TOKEN
ARG LOGLEVEL
ARG OPENROUTESERVICE_KEY
ARG POSTGRES_HOST
ARG ADDOK_HOST
ARG POSTGRES_DB
ARG POSTGRES_USER
ARG POSTGRES_PASSWORD
ARG API_PATH
ARG SUPABASE_URL
ARG SUPABASE_KEY
ARG SUPABASE_TEST_USER
ARG SUPABASE_TEST_PASSWORD
ARG SUPABASE_JWT_SECRET
ARG SUPABASE_ADMIN_KEY

ENV LOGFIRE_TOKEN=$LOGFIRE_TOKEN
ENV LOGLEVEL=$LOGLEVEL
ENV OPENROUTESERVICE_KEY=$OPENROUTESERVICE_KEY
ENV POSTGRES_HOST=$POSTGRES_HOST
ENV ADDOK_HOST=$ADDOK_HOST
ENV POSTGRES_DB=$POSTGRES_DB
ENV POSTGRES_USER=$POSTGRES_USER
ENV POSTGRES_PASSWORD=$POSTGRES_PASSWORD
ENV API_PATH=$API_PATH
ENV SUPABASE_URL=$SUPABASE_URL
ENV SUPABASE_KEY=$SUPABASE_KEY
ENV SUPABASE_TEST_USER=$SUPABASE_TEST_USER
ENV SUPABASE_TEST_PASSWORD=$SUPABASE_TEST_PASSWORD
ENV SUPABASE_JWT_SECRET=$SUPABASE_JWT_SECRET
ENV SUPABASE_ADMIN_KEY=$SUPABASE_ADMIN_KEY

ENV SQLALCHEMY_TRACK_MODIFICATIONS=False

RUN apt update && apt install gcc libpq-dev libgeos-dev

WORKDIR /code

COPY dist/*.whl /code
RUN pip install -U /code/*.whl && rm -f /code/*.whl
EXPOSE 3566
CMD ["hypercorn", "douceville.rest_api_entreypoint:app", "--bind", "0.0.0.0:3566"]
