# docker build -t douceville . --network=host
# docker tag douceville:latest ydethe/douceville:latest
# docker push ydethe/douceville:latest
FROM python:3.11-alpine

ARG LOGFIRE_TOKEN
ARG LOGLEVEL
ARG FLASK_ADMIN_SWATCH
ARG BCRYPT_ROUNDS
ARG SECRET_KEY
ARG OPENROUTESERVICE_KEY
ARG STRIPE_SECRET_KEY
ARG STRIPE_PUBLISHABLE_KEY
ARG MAIL_SERVER
ARG MAIL_PORT
ARG MAIL_USE_TLS
ARG MAIL_USE_SSL
ARG MAIL_USERNAME
ARG MAIL_PASSWORD
ARG MAIL_DEFAULT_SENDER
ARG MAIL_DEBUG
ARG POSTGRES_HOST
ARG POSTGRES_DB
ARG POSTGRES_USER
ARG POSTGRES_PASSWORD
ARG FLASK_INIT_DB
ARG HOST
ARG PORT
ARG PRICE_ID

ENV LOGFIRE_TOKEN=$LOGFIRE_TOKEN
ENV LOGLEVEL=$LOGLEVEL
ENV FLASK_ADMIN_SWATCH=$FLASK_ADMIN_SWATCH
ENV BCRYPT_ROUNDS=$BCRYPT_ROUNDS
ENV SECRET_KEY=$SECRET_KEY
ENV OPENROUTESERVICE_KEY=$OPENROUTESERVICE_KEY
ENV STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY
ENV STRIPE_PUBLISHABLE_KEY=$STRIPE_PUBLISHABLE_KEY
ENV MAIL_SERVER=$MAIL_SERVER
ENV MAIL_PORT=$MAIL_PORT
ENV MAIL_USE_TLS=$MAIL_USE_TLS
ENV MAIL_USE_SSL=$MAIL_USE_SSL
ENV MAIL_USERNAME=$MAIL_USERNAME
ENV MAIL_PASSWORD=$MAIL_PASSWORD
ENV MAIL_DEFAULT_SENDER=$MAIL_DEFAULT_SENDER
ENV MAIL_DEBUG=$MAIL_DEBUG
ENV POSTGRES_HOST=$POSTGRES_HOST
ENV POSTGRES_DB=$POSTGRES_DB
ENV POSTGRES_USER=$POSTGRES_USER
ENV POSTGRES_PASSWORD=$POSTGRES_PASSWORD
ENV FLASK_INIT_DB=$FLASK_INIT_DB
ENV HOST=$HOST
ENV PORT=$PORT
ENV PRICE_ID=$PRICE_ID

ENV SQLALCHEMY_TRACK_MODIFICATIONS=False

RUN apk add --no-cache gcc musl-dev linux-headers postgresql-dev geos-dev

WORKDIR /code
COPY requirements.txt /code
RUN pip install -r requirements.txt

COPY *.whl /code
RUN pip install /code/*.whl
EXPOSE 3566
CMD ["sh", "-c", "uvicorn --host=0.0.0.0 --port 3566 douceville.app:app"]
