name: douceville
channels:
  - conda-forge
  - defaults
dependencies:
  - cryptography<=3.3.1
  - email-validator<=1.1.2
  - flask-admin<=1.5.7
  # - flask-alembic<=2.0.1
  - flask-bcrypt<=0.7.1
  - flask-bootstrap<=3.3.7.1
  - flask-login<=0.4.1
  - flask-mail<=0.9.1
  - Flask-Migrate<=2.6.0
  - flask-nav<=0.6
  # - flask-shell-ipython<=0.4.1
  - flask-sqlalchemy<=2.4.4
  - flask-wtf<=0.14.3
  - flask<=1.1.2
  - GeoAlchemy2<=0.8.4
  - geojson<=2.5.0
  - itsdangerous<=2.0.1
  - jinja2<=2.11.2
  - MarkupSafe<=1.1.1
  - openpyxl<=3.0.6
  # - openrouteservice<=2.3.3
  - pandas<=1.2.1
  - psycopg2-binary<=2.8.6
  - pyopenssl<=20.0.1
  - python-slugify<=4.0.1
  - PyYaml<=5.4.1
  - rdflib<=6.0.1
  # - rdfpandas<=1.1.1
  - rich<=13.0.1
  - shapely<=1.7.1
  - sqlalchemy<=1.4.0
  # - stripe<=5.0.0
  - typer<=0.7.0
  - gunicorn<=20.1.0
  - werkzeug<=1.0.1
  - wtforms<=3.0.0
  - xlrd<=2.0.1
  - python>=3.8
  - pip
  - pip:
    - flask-alembic<=2.0.1
    - rdfpandas<=1.1.1
    - openrouteservice<=2.3.3
    - stripe<=5.0.0
    - flask-shell-ipython<=0.4.1
