[project]
name = "douceville"
dynamic = ["version"]
description = ""
authors = [
    { name = "Yann de Thé", email = "yann@gmail.com" },
]
dependencies = [
    # Requirements dated 30/01/2021
    "cryptography==3.3.1",
    "email-validator==1.1.2",
    "flask-admin==1.5.7",
    "flask-alembic==2.0.1",
    "flask-bcrypt==0.7.1",
    "flask-bootstrap==3.3.7.1",
    "flask-login==0.4.1",
    "flask-mail==0.9.1",
    "Flask-Migrate==2.6.0",
    "flask-nav==0.6",
    "flask-shell-ipython==0.4.1",
    "flask-sqlalchemy==2.4.4",
    "flask-wtf==0.14.3",
    "flask==1.1.2",
    "GeoAlchemy2==0.8.4",
    "geojson==2.5.0",
    "itsdangerous==2.0.1",
    "jinja2==2.11.2",
    "MarkupSafe==1.1.1",
    "openpyxl==3.0.6",
    "openrouteservice==2.3.3",
    "psycopg2-binary==2.8.6",
    "pyopenssl==20.0.1",
    "python-slugify==4.0.1",
    "PyYaml==5.4.1",
    "rdflib==6.0.1",
    "rdfpandas>=1.1.1",
    "rich==13.0.1",
    "shapely==1.7.1",
    "sqlalchemy==1.4.0",
    "stripe==5.0.0",
    "typer==0.7.0",
    "gunicorn==20.1.0",
    "werkzeug==1.0.1",
    "wtforms==3.0.0",
    "xlrd==2.0.1"
]
requires-python = ">=3.8,<3.12"

[project.urls]
"Bug Tracker" = "https://gitlab.com/ydethe/douceville/-/issues"
Homepage = "https://gitlab.com/ydethe/douceville"
Source = "https://gitlab.com/ydethe/douceville"

[tool.pylint.main]
ignore-patterns = ["kt_*.py"]

[tool.pylint.format]
max-line-length = 100

[tool.black]
line-length = 100
target-version = ['py38']
force-exclude = 'kt_.*.py'

[project.scripts]
maillage = "douceville.scripts.import_etablissements:import_main"
conv_geoloc_enseignement = "douceville.scripts.conv_geoloc_enseignement:conv_geoloc_enseignement_main"
conv_rdf = "douceville.scripts.conv_rdf:conv_rdf_main"
dv_users = "douceville.blueprints.users.manage_users:add_user_main"

[project.optional-dependencies]
[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"

[tool.pdm.version]
source = "scm"

[tool.pdm.build]
includes = [
    "douceville/",
]
excludes = [
    "tests",
    "build",
    "dist",
]

[tool.pdm.dev-dependencies]
dev = [
    "ipython~=7.23.1",
    "black==22.3.0",
    "pandas==1.5.3",
]
doc = [
    "pdoc3~=0.10.0",
    "pylint~=2.15.3",
]
test = [
    "pytest~=7.1.3",
    "pytest-cov~=3.0.0",
    "pytest-xdist~=2.5.0",
    "pytest-mock~=3.8.2",
    "pytest-instafail~=0.4.2",
    "pytest-picked~=0.4.6",
    "pytest-sugar~=0.9.5",
    "pytest-html~=3.1.1",
]

[tool.pdm.scripts]
site_packages = true
test.shell = """\
    mkdir -p build/htmldoc/tests
    pytest --html=build/htmldoc/tests/report.html --self-contained-html --junitxml=build/junit.xml --cov-config=.coveragerc --cov douceville tests --doctest-modules douceville
    coverage html -d build/htmldoc/coverage
"""
doc.shell = """\
    mkdir -p build/htmldoc/douceville
    mkdir -p build/htmldoc/examples
    python -m ipykernel install --user
    python examples/__init__.py
    cp examples/quadcopter.png build/htmldoc/examples
    pdoc --html --force --config latex_math=True --template-dir dev/template -o build/htmldoc douceville examples
    pyreverse -s0 douceville -k --colorized -p douceville -m no --ignore=exceptions.py,LogFormatter.py,CSVLogger.py,PickleLogger.py,XlsLogger.py -d build/htmldoc
    dot -Tpng build/htmldoc/classes_douceville.dot -o build/htmldoc/douceville/classes.png
"""
