from sqlalchemy import Column, String, Integer, Boolean
from sqlalchemy.ext.declarative import declarative_base


Base = declarative_base()

class Lycee(Base):
    __tablename__ = 'lycee'
    UAI              = Column(String, primary_key=True)
    nom              = Column(String)
    academie         = Column(String)
    departement      = Column(Integer)
    secteur_prive    = Column(Boolean)
    commune          = Column(String)
    taux_2nde_bac    = Column(Integer)
    va_2nde_bac      = Column(Integer)
    taux_1ere_bac    = Column(Integer)
    va_1ere_bac      = Column(Integer)
    taux_term_bac    = Column(Integer)
    va_term_bac      = Column(Integer)
    presents_gt      = Column(Integer)
    admis_gt         = Column(Integer)
    va_admis_gt      = Column(Integer)
    presents_l       = Column(Integer)
    admis_l          = Column(Integer)
    va_admis_l       = Column(Integer)
    presents_es      = Column(Integer)
    admis_es         = Column(Integer)
    va_admis_es      = Column(Integer)
    presents_s       = Column(Integer)
    admis_s          = Column(Integer)
    va_admis_s       = Column(Integer)
    presents_stmg    = Column(Integer)
    admis_stmg       = Column(Integer)
    va_admis_stmg    = Column(Integer)
    presents_stl     = Column(Integer)
    admis_stl        = Column(Integer)
    va_admis_stl     = Column(Integer)
    presents_st2s    = Column(Integer)
    admis_st2s       = Column(Integer)
    va_admis_st2s    = Column(Integer)
    presents_sti2d   = Column(Integer)
    admis_sti2d      = Column(Integer)
    va_admis_sti2d   = Column(Integer)
    presents_std2a   = Column(Integer)
    admis_std2a      = Column(Integer)
    va_admis_std2a   = Column(Integer)
    presents_tmd     = Column(Integer)
    admis_tmd        = Column(Integer)
    va_admis_tmd     = Column(Integer)
    presents_sthr    = Column(Integer)
    admis_sthr       = Column(Integer)
    va_admis_sthr    = Column(Integer)
    mentions_gt      = Column(Integer)
    va_mention_gt    = Column(Integer)
    mentions_l       = Column(Integer)
    va_mention_l     = Column(Integer)
    mentions_es      = Column(Integer)
    va_mention_es    = Column(Integer)
    mentions_s       = Column(Integer)
    va_mention_s     = Column(Integer)
    mentions_stmg    = Column(Integer)
    va_mention_stmg  = Column(Integer)
    mentions_stl     = Column(Integer)
    va_mention_stl   = Column(Integer)
    mentions_st2s    = Column(Integer)
    va_mention_st2s  = Column(Integer)
    mentions_sti2d   = Column(Integer)
    va_mention_sti2d = Column(Integer)
    mentions_std2a   = Column(Integer)
    va_mention_std2a = Column(Integer)
    mentions_tmd     = Column(Integer)
    va_mention_tmd   = Column(Integer)
    mentions_sthr    = Column(Integer)
    va_mention_sthr  = Column(Integer)


if __name__ == '__main__':
    from sqlalchemy import create_engine
    engine = create_engine('sqlite:///lycee.db')

    from sqlalchemy.orm import sessionmaker
    session = sessionmaker()
    session.configure(bind=engine)
    Base.metadata.create_all(engine)
