"""empty message

Revision ID: 3183508f12f8
Revises: e913540f8ea6
Create Date: 2020-10-21 23:24:15.531115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3183508f12f8'
down_revision = 'e913540f8ea6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.add_column('etablissement', sa.Column('nature', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('etablissement', 'nature')
    # ### end Alembic commands ###
