"""empty message

Revision ID: e913540f8ea6
Revises: a65bc325de9e
Create Date: 2020-10-21 22:43:38.600294

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from geoalchemy2.types import Geometry

# revision identifiers, used by Alembic.
revision = "e913540f8ea6"
down_revision = "a65bc325de9e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("etablissement", sa.Column("adresse", sa.String(), nullable=True))
    op.add_column("etablissement", sa.Column("code_postal", sa.String(), nullable=True))
    op.add_column("etablissement", sa.Column("lieu_dit", sa.String(), nullable=True))
    op.add_column("etablissement", sa.Column("ouverture", sa.DateTime(), nullable=True))
    op.add_column(
        "etablissement",
        sa.Column(
            "position",
            Geometry(
                geometry_type="POINT", from_text="ST_GeomFromEWKT", name="geometry"
            ),
            nullable=True,
        ),
    )
    op.drop_column("etablissement", "latitude")
    op.drop_column("etablissement", "longitude")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "etablissement",
        sa.Column(
            "longitude",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "etablissement",
        sa.Column(
            "latitude",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("etablissement", "position")
    op.drop_column("etablissement", "ouverture")
    op.drop_column("etablissement", "lieu_dit")
    op.drop_column("etablissement", "code_postal")
    op.drop_column("etablissement", "adresse")
    # ### end Alembic commands ###
