name: Docker Image CI

on:
  push:
    tags:
      - '**'

jobs:
  build_wheel:
    name: Publication workflow
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Build wheel and install
        run: |
          python -m pip install --user --upgrade build
          python -m build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Python wheel file
          path: dist/*.whl

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ydethe/douceville-backend

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
